### PR TITLE
Add support for injecting environment variables

### PR DESCRIPTION
**Pull request by jraede**
* jshint/jsbeautify cleanup
* Only append environment/version to function name if they are provided (no longer defaults)

### CODE REVIEW

**Comment by motdotla** [comment]
This look good @jraede. Thanks much. :100: 

If you get the chance, can you rebase to make it ready for an automatic merge. If I get to it first, I'll do so instead.

**Comment by jraede** [comment]
@motdotla  I rebased and ran the tests, so it should be good to go. Thanks for the quick turnaround!

**Comment by motdotla** [comment]
Thanks again. Released in `0.6.0`

**Comment by jraede** [comment]
:+1:

**Pull request merged**
