### PR TITLE
Lambda new api

### PR DESCRIPTION
**Pull request by jadbox**
I've updated node-lambda to support version 2015-03-31 of Amazon's API.

### CODE REVIEW

**Comment by motdotla** [comment]
Thanks for the PR @jadbox! This is currently failing tests though. Could you please get it passing?

**Comment by motdotla** [comment]
Closing. Older now. Will re-open with passing tests.

**Comment by jadbox** [comment]
Sorry, I've been pulled into other things. I'll try to loop back on this eventually.

**Comment by motdotla** [comment]
No problem. By the way, welcome to Santa Monica! :surfer: 

I'm from here. If you're ever down for a :coffee:, let me know.

**Comment by jadbox** [comment]
@motdotla Let's! I'll shoot you an email =]

**Pull request closed without merging**
